export const booksData =[
  { id:1,
  img:"https://images-na.ssl-images-amazon.com/images/I/81WuEQjTE1L._AC_UL200_SR200,200_.jpg",
  title: "The Princess Spy: The True Story of World War II Spy Aline Griffith, Countess of Romanones",
  author: "Larry Loftis",
},
{id:2,
  img:"https://images-na.ssl-images-amazon.com/images/I/91pR9wKJ3zL._AC_UL200_SR200,200_.jpg",
  title: "Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones ",
  author: "James Clear",
},
{id:3,
  img:"https://images-na.ssl-images-amazon.com/images/I/41bChkOa4zL._AC_UL200_SR200,200_.jpg",
  title: "Think Again: The Power of Knowing What You Don't Know",
  author: "Adam Grant",
},

{id:4,
  img:"https://images-na.ssl-images-amazon.com/images/I/61NTRR5fjDL._AC_UL200_SR200,200_.jpg",
  title: "The Body Keeps the Score: Brain, Mind, and Body in the Healing of Trauma",
  author: "Bessel Van Der Kolk M.D.",
},

{id:5,
  img:"https://images-na.ssl-images-amazon.com/images/I/41bChkOa4zL._AC_UL200_SR200,200_.jpg",
  title: "Think Again: The Power of Knowing What You Don't Know",
  author: "Adam Grant",
},

{id:6,
  img:"https://images-na.ssl-images-amazon.com/images/I/41bChkOa4zL._AC_UL200_SR200,200_.jpg",
  title: "Think Again: The Power of Knowing What You Don't Know",
  author: "Adam Grant",
},

{id:7,
  img:"https://images-na.ssl-images-amazon.com/images/I/41bChkOa4zL._AC_UL200_SR200,200_.jpg",
  title: "Think Again: The Power of Knowing What You Don't Know",
  author: "Adam Grant",
},

{id:8,
  img:"https://images-na.ssl-images-amazon.com/images/I/41bChkOa4zL._AC_UL200_SR200,200_.jpg",
  title: "Think Again: The Power of Knowing What You Don't Know",
  author: "Adam Grant",
},

{id:9,
  img:"https://images-na.ssl-images-amazon.com/images/I/41bChkOa4zL._AC_UL200_SR200,200_.jpg",
  title: "Think Again: The Power of Knowing What You Don't Know",
  author: "Adam Grant",
},

{id:10,
  img:"https://images-na.ssl-images-amazon.com/images/I/41bChkOa4zL._AC_UL200_SR200,200_.jpg",
  title: "Think Again: The Power of Knowing What You Don't Know",
  author: "Adam Grant",
},

{id:11,
  img:"https://images-na.ssl-images-amazon.com/images/I/41bChkOa4zL._AC_UL200_SR200,200_.jpg",
  title: "Think Again: The Power of Knowing What You Don't Know",
  author: "Adam Grant",
},

{id:12,
  img:"https://images-na.ssl-images-amazon.com/images/I/41bChkOa4zL._AC_UL200_SR200,200_.jpg",
  title: "Think Again: The Power of Knowing What You Don't Know",
  author: "Adam Grant",
},

];

